name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy code
        run: |
          echo "${{ secrets.PASSWORD }}" | rsync -avz --delete-after --exclude '.git/' $GITHUB_WORKSPACE ubuntu@3.111.69.219:/var/www/html
