name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install -y rsync sshpass

      - name: Deploy code
        run: |
         sshpass -p "${{ secrets.PASSWORD }}" rsync -e 'ssh -o StrictHostKeyChecking=no' -avz --delete-after --exclude '.git/' $GITHUB_WORKSPACE/* "${{ secrets.SERVER_USERNAME }}"@"${{ secrets.SSH_HOST }}":"${{ secrets.SERVER_PATH }}"
