name: PHP CI/CD with AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Replace with your desired PHP version


   

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        scp -i ${{ secrets./root/.ssh/id_rsa }} -r ./ ubuntu@3.111.69.219:/var/www/html
        ssh -i ${{ secrets./root/.ssh/id_rsa }} ubuntu@3.111.69.219 'cd /var/www/html && ./deploy.sh'
